### ISSUE TITLE
Function to safely acquire and register resources?

### ISSUE THREAD

**Issue by massysett** [Gabriel439/Haskell-Pipes-Safe-Library#21]
Have you ever thought about adding a function like this?

```
acquire :: MonadSafe m => Base m a -> (a -> Base m ()) -> m a
acquire acq rel = mask $ \restore -> do
    a <- liftBase acq
    _ <- register (rel a)
    -- I'm not sure the 'restore' is needed here
    restore $ return a
```

I've found it a useful idiom, though I do wonder if there is a better idiom for this using existing functions and I'm just not aware of it.  Thanks.  --Omari

**Comment by chris-martin** [comment]
Perhaps some of the API from `resourcet` could be mimicked? https://hackage.haskell.org/package/resourcet-1.2.4.3/docs/Control-Monad-Trans-Resource.html#g:6
