### ISSUE TITLE
Build fails on GHC 7.4, even though there is an install plan

### ISSUE THREAD

**Issue by phadej** [Gabriel439/Haskell-Pipes-Safe-Library#27]
See http://matrix.hackage.haskell.org/package/pipes-safe#GHC-7.4/pipes-safe-2.2.4

btw. `pipes` have build-plan and compile on 7.4 though you don't test it on travis. I guess this is because of non-buildable benchmarks? See https://github.com/AtnNn/haskell-rethinkdb/pull/64/commits/d55967bc05f91f91e6743dd3ab0ec0c39dc07f03 there I add `NOBENCH=YES` parameter to not build benchmarks with some GHC. I can make PR to this and `pipes` repositories if that functionality is desirable (i.e. you want to support GHC 7.4)

**Comment by Gabriel439** [comment]
I fixed it to build on GHC 7.4  The actual reason it failed was due to the use of `atomicModifyIORef'` which was introduced in GHC 7.6.  I modified the code to use the non-strict version for older versions of `base`.
