### ISSUE TITLE
Flushing the pipeline on error

### ISSUE THREAD

**Issue by 3noch** [Gabriel439/Haskell-Pipes-Safe-Library#31]
I have an app that was suffering from a problem with buffering (data never made it into the output file). It seems like there should be a way to set up a pipeline that flushes on [some] exceptions. In my case, the app never ends and `Ctrl+C` is how I tell it to stop writing data. Does such a thing exist already?

**Comment by Gabriel439** [comment]
So I think this is superseded by #30 since if we fix the finalization error that you ran into then `hClose` should run and flush the data on any exceptions

**Comment by 3noch** [comment]
Yes I was not aware that `hClose` did a flush, so this is a separate issue.
